### ISSUE TITLE
Hand detection module is slow 

### ISSUE THREAD

**Issue by shimiaoli** [moberweger/deep-prior#2]
Hi @moberweger ,

When I test the code, I've found that most of the computation time (about 50%) is spent on hand detection module. I guess this is due to the com refinement network during hand detection. Is this refinement important for final performance ?

Thank you .

**Comment by moberweger** [comment]
Hi @shimiaoli 
Indeed this is the a slow part. There are two detection modes (press "t" to switch), which are center of mass detection and using the refinement network. You can evaluate the accuracy change by yourself, but for me it is significantly more stable and more accurate when using the refinement network. Since this implementation is only using a single thread, there would be many ways to increase the performance, if necessary.

**Comment by shimiaoli** [comment]
Thank you. @moberweger 
I have tested disabling the com refinement net during hand detection. The performance does not seem to change much on ICVL dataset but accuracy does drop on NYU dataset.  I think this is because hand center changes more in NYU dataset than ICVL.  Speed is slightly faster  (about 10% faster while using GPU, about 20-30% faster while using CPU only).

**Comment by shimiaoli** [comment]
@moberweger 
Another question is: it seems pose estimation does not include refinement network in this implementation? Is it for speed consideration?

**Comment by moberweger** [comment]
@shimiaoli 
as far as I can see the refinement is implemented trough HandDetector::track, and is only used for the tracking option. But of course, you could add it on top of the detection result. However, I experienced no increase in accuracy for this configuration.
